version: '2.1'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  postgresql-fry:
    image: postgres:12.3-alpine
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=fry
    ports:
      - 5432:5432

  postgresql-fry-test:
    image: postgres:12.3-alpine
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=fry
    ports:
      - 25432:5432